use sha2::{Digest, Sha256};
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    // Tauri's required build step
    tauri_build::build();

    // ── License secret obfuscation (SEC-05) ────────────────────────────────
    // Both secrets are XOR-ed with a salt derived from the build environment.
    // The salt itself is also embedded but XOR-ed with a per-build static
    // constant, so a naive `strings` attack yields only obfuscated bytes.
    //
    // This is not cryptographically strong — an attacker with a disassembler
    // can recover the secrets. It raises the bar from "10 seconds" to
    // "needs to understand the scheme and follow XOR through OnceLock decode".

    let pkg_version = std::env::var("CARGO_PKG_VERSION").unwrap_or_default();
    let pkg_name = std::env::var("CARGO_PKG_NAME").unwrap_or_default();

    // Salt: deterministic per build (so dev/prod builds are reproducible)
    let salt_seed = format!("{pkg_name}@{pkg_version}::RoFactura-build-salt-2026");
    let salt: [u8; 32] = Sha256::digest(salt_seed.as_bytes()).into();

    // The original secrets — only present in source, NOT in compiled binary
    let integrity_secret: &[u8] = b"RoF@ctura#2026!intgr1ty_K3y\xd4\x9a\x7f\x01\xbe\xc3v2";
    let key_hmac_secret: &[u8] = b"RoF@ctura#Key!HMAC2026\xb2\x7f\xd4\x91\xc3\x0a";

    // XOR-cycle each secret against the salt
    let int_obf: Vec<u8> = integrity_secret
        .iter()
        .zip(salt.iter().cycle())
        .map(|(b, s)| b ^ s)
        .collect();

    let hmac_obf: Vec<u8> = key_hmac_secret
        .iter()
        .zip(salt.iter().cycle())
        .map(|(b, s)| b ^ s)
        .collect();

    // Mask the salt itself with a static (so the salt isn't naked in the binary)
    let salt_mask: [u8; 32] = Sha256::digest(b"RoFactura-salt-mask-v1").into();
    let salt_masked: Vec<u8> = salt
        .iter()
        .zip(salt_mask.iter())
        .map(|(a, b)| a ^ b)
        .collect();

    fn fmt_array(name: &str, bytes: &[u8]) -> String {
        let hex: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
        format!("const {name}: &[u8] = &[{}];", hex.join(","))
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — DO NOT EDIT\n");
    out.push_str("// SEC-05: obfuscated license secrets\n\n");
    out.push_str(&fmt_array("_INT_OBF", &int_obf));
    out.push('\n');
    out.push_str(&fmt_array("_HMAC_OBF", &hmac_obf));
    out.push('\n');
    out.push_str(&fmt_array("_SALT_MASKED", &salt_masked));
    out.push('\n');
    out.push_str(&fmt_array("_SALT_MASK", &salt_mask));
    out.push('\n');

    out.push_str(
        r#"
fn _decode_salt() -> [u8; 32] {
    let mut salt = [0u8; 32];
    for (i, (a, b)) in _SALT_MASKED.iter().zip(_SALT_MASK.iter()).enumerate() {
        salt[i] = a ^ b;
    }
    salt
}

fn _decode_obf(obf: &[u8]) -> Vec<u8> {
    let salt = _decode_salt();
    obf.iter()
        .zip(salt.iter().cycle())
        .map(|(a, b)| a ^ b)
        .collect()
}

fn integrity_secret_bytes() -> Vec<u8> {
    _decode_obf(_INT_OBF)
}

fn key_hmac_secret_bytes() -> Vec<u8> {
    _decode_obf(_HMAC_OBF)
}
"#,
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("license_secrets.rs");
    let mut f = fs::File::create(&dest).expect("create license_secrets.rs");
    f.write_all(out.as_bytes())
        .expect("write license_secrets.rs");

    // Rebuild trigger
    println!("cargo:rerun-if-changed=build.rs");
}
