//! Wave C — multi-source data-migration importer.
//!
//! W1 (this wave): staging schema + ImportAdapter trait + WinMentor TXT adapter (parse-only).
//! W2: SmartBill XML + SAGA XML adapters.
//! W3: SAGA DBF + SmartBill REST adapters.
//! W4: commit engine (staging → live tables).
//! W5: UI wiring + Tauri commands.
//!
//! No Tauri commands are registered here yet — see W4/W5.

pub mod adapter;
pub mod saga_dbf;
pub mod saga_xml;
pub mod smartbill_rest;
pub mod smartbill_xml;
pub mod winmentor;
pub mod xml_common;

// W3 re-exports for W4 convenience.
pub use saga_dbf::SagaDbfAdapter;
pub use smartbill_rest::{
    fetch_smartbill, map_stocks_json, SmartBillCreds, SmartBillResource, SmartBillRestAdapter,
};

// ─── SourceKind ─────────────────────────────────────────────────────────────

/// Which external system the import file/stream originates from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SourceKind {
    SmartbillXml,
    SmartbillRest,
    SagaXml,
    SagaDbf,
    WinmentorTxt,
}

impl std::fmt::Display for SourceKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            SourceKind::SmartbillXml => "SMARTBILL_XML",
            SourceKind::SmartbillRest => "SMARTBILL_REST",
            SourceKind::SagaXml => "SAGA_XML",
            SourceKind::SagaDbf => "SAGA_DBF",
            SourceKind::WinmentorTxt => "WINMENTOR_TXT",
        };
        write!(f, "{s}")
    }
}

// ─── ImportInput ────────────────────────────────────────────────────────────

/// The raw data handed to an adapter for parsing.
pub enum ImportInput {
    /// Raw file bytes (TXT / XML / DBF / ZIP).
    Bytes(Vec<u8>),
    /// One or more file paths (e.g. Partener.txt + Articole.txt + invoice.txt).
    Files(Vec<std::path::PathBuf>),
    /// REST-API credentials (used by SmartBillRest adapter in W3).
    RestCreds { company_id: String },
}

// ─── ColumnMap ──────────────────────────────────────────────────────────────

/// User-confirmed mapping from source header/key → internal field name.
/// Used by DEFENSIVE adapters that present an "are these columns right?" dialog
/// before committing. The WinMentor adapter uses the documented key names by
/// default but respects overrides here (e.g. CUI vs CodExtern for partner ID).
pub type ColumnMap = std::collections::HashMap<String, String>;

/// A discovered column/key name together with a sample value, for the UI preview.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DetectedColumn {
    pub name: String,
    pub sample: String,
}

// ─── ParseCtx ───────────────────────────────────────────────────────────────

/// Context supplied to every adapter at parse time.
pub struct ParseCtx<'a> {
    /// Canonical CUI of the company being imported INTO (used to detect
    /// ISSUED vs RECEIVED direction on invoice packages).
    pub company_cui_canonical: &'a str,
    /// Optional user-confirmed column map (overrides adapter defaults).
    pub column_map: Option<&'a ColumnMap>,
}

// ─── Staged-data structs ─────────────────────────────────────────────────────
// These mirror the import_staging_* tables defined in migration 0056.
// Monetary/quantity fields are String (Decimal-as-TEXT convention).

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedContact {
    /// UUID generated by the adapter; matches import_staging_contact.id.
    pub id: String,
    pub source: String,
    /// Serialised raw source record (for audit).
    pub raw_json: String,
    pub source_code: Option<String>,
    pub contact_type: Option<String>,
    pub cui_raw: Option<String>,
    pub cui_canonical: Option<String>,
    pub legal_name: Option<String>,
    pub vat_payer: Option<bool>,
    pub is_individual: Option<bool>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub county: Option<String>,
    pub country: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    /// Dedup key (canonical CUI, stripped of leading zeros, for fast matching).
    pub dedup_key: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedProduct {
    pub id: String,
    pub source: String,
    pub raw_json: String,
    pub source_code: Option<String>,
    pub name: Option<String>,
    pub unit: Option<String>,
    pub unit_price: Option<String>,
    pub vat_rate: Option<String>,
    pub vat_category: Option<String>,
    pub code: Option<String>,
    pub barcode: Option<String>,
    pub stock_qty: Option<String>,
    pub is_service: Option<bool>,
    pub dedup_key: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedAccount {
    pub id: String,
    pub source: String,
    pub raw_json: String,
    pub account_code: Option<String>,
    pub synthetic_code: Option<String>,
    pub analytic_suffix: Option<String>,
    pub account_name: Option<String>,
    /// First digit of account_code (RO plan de conturi class 1-9).
    pub account_class: Option<i32>,
    pub dedup_key: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedLine {
    pub id: String,
    pub position: i32,
    pub name: Option<String>,
    pub description: Option<String>,
    pub product_code: Option<String>,
    pub quantity: Option<String>,
    pub unit: Option<String>,
    pub unit_price: Option<String>,
    pub vat_rate: Option<String>,
    pub vat_category: Option<String>,
    pub subtotal_amount: Option<String>,
    pub vat_amount: Option<String>,
    pub total_amount: Option<String>,
    pub account_code: Option<String>,
    pub warehouse: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedInvoice {
    pub id: String,
    pub source: String,
    pub raw_json: String,
    /// 'ISSUED' | 'RECEIVED'
    pub direction: String,
    pub external_id: Option<String>,
    pub partner_cui_canonical: Option<String>,
    pub partner_name: Option<String>,
    pub series: Option<String>,
    pub number: Option<String>,
    pub full_number: Option<String>,
    pub issue_date: Option<String>,
    pub due_date: Option<String>,
    pub currency: Option<String>,
    pub exchange_rate: Option<f64>,
    pub reverse_charge: Option<bool>,
    pub cash_vat: Option<bool>,
    pub subtotal_amount: Option<String>,
    pub vat_amount: Option<String>,
    pub total_amount: Option<String>,
    pub dedup_key: Option<String>,
    pub lines: Vec<StagedLine>,
}

/// The aggregate result of a single `parse()` call. Does NOT touch the DB.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct StagedData {
    pub contacts: Vec<StagedContact>,
    pub products: Vec<StagedProduct>,
    pub accounts: Vec<StagedAccount>,
    pub invoices: Vec<StagedInvoice>,
    /// Non-fatal warnings (unknown keys, skipped sections, etc.).
    pub warnings: Vec<String>,
}

impl StagedData {
    pub fn empty() -> Self {
        StagedData {
            contacts: vec![],
            products: vec![],
            accounts: vec![],
            invoices: vec![],
            warnings: vec![],
        }
    }
}

// ─── canonical_cui helper ────────────────────────────────────────────────────

/// Normalise a Romanian CUI/CIF for use as a dedup key.
///
/// Chain (matches contacts.rs normalization + strips leading zeros for staging):
///   1. trim whitespace
///   2. uppercase
///   3. strip leading "RO" (VAT-payer prefix is not part of identity)
///   4. trim again (handles "RO 123" with interior space)
///   5. strip leading ASCII zeros (canonical numeric identity; "0123" == "123")
///
/// The result is purely numeric for valid RO CUIs. Foreign VAT ids
/// (non-numeric after strip) are returned as-is (uppercased, trimmed).
pub fn canonical_cui(raw: &str) -> String {
    let s = raw.trim().to_uppercase();
    let s = s.strip_prefix("RO").unwrap_or(&s);
    let s = s.trim();
    // Strip leading zeros so "0123", "000", and "123" all compare equal.
    let stripped = s.trim_start_matches('0');
    if stripped.is_empty() {
        // Input was all zeros (or empty after stripping RO).
        // Return "0" when there was at least one zero digit (dedup: "000" == "0").
        // Return "" when there was truly nothing.
        if s.is_empty() {
            String::new()
        } else {
            "0".to_string()
        }
    } else {
        stripped.to_string()
    }
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_cui_strips_ro_prefix_and_leading_zeros() {
        // "RO 0123" and "123" must produce the same key.
        assert_eq!(canonical_cui("RO 0123"), canonical_cui("123"));
        // Lowercase prefix also stripped.
        assert_eq!(canonical_cui("ro0123"), canonical_cui("123"));
        // No prefix, no zeros.
        assert_eq!(canonical_cui("12345678"), "12345678");
        // Already canonical.
        assert_eq!(canonical_cui("1234567"), "1234567");
        // Interior spaces in prefix area handled.
        assert_eq!(canonical_cui("RO  007"), "7");
        // All zeros → "0" not empty.
        assert_eq!(canonical_cui("000"), "0");
        // Bare zero.
        assert_eq!(canonical_cui("0"), "0");
        // Trimming whitespace.
        assert_eq!(canonical_cui("  RO 256644  "), "256644");
    }

    #[test]
    fn canonical_cui_roundtrip_ro_prefix_variants() {
        // The brief explicitly lists "RO12345678" (VAT-payer form) and "12345678"
        // (non-VAT-payer form) as the SAME legal entity.
        let with_prefix = canonical_cui("RO12345678");
        let without_prefix = canonical_cui("12345678");
        assert_eq!(with_prefix, without_prefix);
    }
}
